### ISSUE TITLE
Dungeon 

### ISSUE THREAD

**Issue by babypeach7929** [xd3v0nx/Project_EscapingAlderwood#4]
> After getting the dagger, how do I use it?

**Comment by babypeach7929** [comment]
> After retrieving Thomas, is there an actual way out of the dungeon?

**Comment by xd3v0nx** [comment]
@isnizal  don't begin working on the next version yet, but I will want to have a more visual way that players can use weapons from their arsenal. I was thinking maybe a "Weapon Wheel" of some sort. Essentially like they do in Resident Evil games, thing is we will pick up weapons along the way, first of which is the dagger... in the next level we will have our hands on the Warden's bow, giving us a distance weapon. We need to make the dagger a melee weapon, rather than something we throw. We also need a better way to dodge the guards, there is not a lot of room to move around the guards, and we also want more obstacles, but we will touch on those later. Do not change anything yet, I am working on collecting more feedback for us, then we will begin working on v1.2.0

**Comment by isnizal** [comment]
> @isnizal  don't begin working on the next version yet, but I will want to have a more visual way that players can use weapons from their arsenal. I was thinking maybe a "Weapon Wheel" of some sort. Essentially like they do in Resident Evil games, thing is we will pick up weapons along the way, first of which is the dagger... in the next level we will have our hands on the Warden's bow, giving us a distance weapon. We need to make the dagger a melee weapon, rather than something we throw. We also need a better way to dodge the guards, there is not a lot of room to move around the guards, and we also want more obstacles, but we will touch on those later. Do not change anything yet, I am working on collecting more feedback for us, then we will begin working on v1.2.0

I did some android api update to 34. Okay, I only change that into V1.1.1

**Comment by isnizal** [comment]
> > After getting the dagger, how do I use it?

On Android, Just press the dagger icon on the right side. On PC, you will need to press the space bar.

**Comment by isnizal** [comment]
> > After retrieving Thomas, is there an actual way out of the dungeon?

Yes, there is a way out.
