### ISSUE TITLE
My views 

### ISSUE THREAD

**Issue by RealcyprianK** [xd3v0nx/Project_EscapingAlderwood#5]
As a prototype nothing wrong with that, how the layout and limited actions are right now.

It can be great to include the instructions when the prototype loads up. That way while moving after getting the knife and avoiding the guards.

Within the prototype unlike going to read the levels separately.

I have strong thoughts on the next prototype version, continue the brilliant work. Can't wait for new updates!

**Comment by isnizal** [comment]
Instruction? That is a good idea to add especially the UI.

**Comment by xd3v0nx** [comment]
@isnizal  @RealcyprianK  what I am thinking is, we could have a "question mark" icon in the right hand corner of the screen, containing the instructions and controls. Honestly, we need to have these visible, otherwise how is anyone going to know how to play the game? For now, this would be a simple yet effective strategy.
